let currentStudent=null,selectedTags=[],currentProjectId=null,currentWizardStep=0,recommendedItems=[],recommendationPage=0,teacherPassword='';
const TAGS=['게임','스포츠','음악','K-POP','유튜브','웹툰','영화','음식','환경','친구관계','스마트폰','진로','과학','로봇','AI','건강','학교생활'];
const WIZARD_PAGES=['wizardPlan','wizardGuide','wizardSurvey','wizardInterview','wizardLog','wizardReport','wizardPrint'];
const WIZARD_PROGRESS=[30,45,60,70,80,90,100];
const PAGE_SIZE=5;
window.onload=()=>{const t=document.getElementById('tags');if(t)t.innerHTML=TAGS.map(x=>`<span class="tag" onclick="selectTag(this,'${x}')">${x}</span>`).join('');initWizardPage();initAiSettingsPage();initInternetStatus();};
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function valueOf(id){return document.getElementById(id)?.value||'';}function setValue(id,v){const e=document.getElementById(id);if(e)e.value=v||'';}function clamp(v){return Math.max(0,Math.min(100,Math.round(Number(v||0))));}
async function post(url,data){return await (await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).json();}
function selectTag(el,tag){if(selectedTags.includes(tag)){selectedTags=selectedTags.filter(x=>x!==tag);el.classList.remove('active');return;}if(selectedTags.length>=2)return alert('관심사는 최대 2개까지 선택할 수 있습니다.');selectedTags.push(tag);el.classList.add('active');}
function getInterestQuery(){const detail=valueOf('detail').trim();return{detail,tagText:selectedTags.join(' + '),queryText:[detail,selectedTags.join(' + ')].filter(Boolean).join(' + ')}};
function setInternetStatus(online){const b=document.getElementById('internetStatus');if(!b)return;b.classList.toggle('online',online);b.classList.toggle('offline',!online);b.innerHTML=`<span class="status-dot"></span><span>${online?'인터넷이 연결되어 있음':'인터넷이 연결되어 있지 않음'}</span>`;}
function initInternetStatus(){const b=document.getElementById('internetStatus');if(!b)return;setInternetStatus(navigator.onLine);window.addEventListener('online',()=>setInternetStatus(true));window.addEventListener('offline',()=>setInternetStatus(false));}
async function login(){const name=valueOf('name').trim(),student_no=valueOf('studentNo').trim();if(!name||!student_no)return alert('학번과 이름을 입력하세요.');currentStudent=await post('/api/student/login',{name,student_no});document.getElementById('loginBox').classList.add('hidden');document.getElementById('interestBox').classList.remove('hidden');await loadMyProjects();}
function renderFeedback(feedbacks=[]){if(!feedbacks.length)return '';return `<div class="feedback-box"><h4>교사 피드백</h4>${feedbacks.map(f=>`<div class="feedback-item"><b>${esc(f.created_at)} · ${f.total_score||0}/20점</b><p>${esc(f.teacher_comment||'')}</p></div>`).join('')}</div>`;}
async function loadMyProjects(){const res=await(await fetch(`/api/student/${currentStudent.id}/projects`)).json();const box=document.getElementById('myProjectsBox'),list=document.getElementById('myProjects');if(!res.items.length){box.classList.add('hidden');return;}box.classList.remove('hidden');list.innerHTML=res.items.map(p=>`<div class="topic"><h3>${esc(p.topic)}</h3><p class="muted">진행률 ${p.progress}% · 적합도 ${p.fit_score}점</p><div class="bar"><span style="width:${clamp(p.progress)}%"></span></div>${renderFeedback(p.feedbacks)}<label class="field-label">진행 상황</label><textarea class="progress-note" id="note${p.id}">${esc(p.progress_note||'')}</textarea><div class="row"><button class="btn secondary" onclick="openProject(${p.id})">이어하기</button><button class="btn" onclick="saveProgressNote(${p.id})">진행 상황 저장</button><button class="btn danger" onclick="deleteProject(${p.id})">삭제</button></div></div>`).join('');}
async function saveProgressNote(id){const res=await fetch(`/api/projects/${id}/progress-note`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({progress_note:valueOf(`note${id}`)})});if(!res.ok)return alert('저장 실패');alert('저장되었습니다.');}
function openProject(id){location.href=`wizard.html?project_id=${id}`;}async function deleteProject(id){if(!confirm('이 탐구를 삭제할까요?'))return;await fetch(`/api/projects/${id}`,{method:'DELETE'});await loadMyProjects();}
async function recommend(){const q=getInterestQuery();if(!q.detail&&!q.tagText)return alert('관심사를 입력하세요.');const res=await post('/api/recommend',{tag:q.tagText,detail:q.detail});recommendedItems=(res.items||[]).slice(0,20);recommendationPage=0;document.getElementById('recommendBox').classList.remove('hidden');document.getElementById('modeText').innerText=`${res.mode==='online'?'온라인 AI':'오프라인'} 추천 결과입니다.`;renderRecommendations();}
function renderRecommendations(){const start=recommendationPage*PAGE_SIZE,items=recommendedItems.slice(start,start+PAGE_SIZE),pages=Math.max(1,Math.ceil(recommendedItems.length/PAGE_SIZE));document.getElementById('topics').innerHTML=items.map(it=>`<div class="topic"><h3>${esc(it.topic)}</h3><p><b>교과</b> ${esc(it.subject)} · <b>유형</b> ${esc(it.inquiry_type)} · <b>기간</b> ${esc(it.duration)}</p><p class="muted">${esc(it.reason)}</p><div class="score">${it.fit?.total||70}점</div><div class="bar"><span style="width:${clamp(it.fit?.total||70)}%"></span></div><button class="btn" onclick='startProject(${JSON.stringify(it).replace(/'/g,'&#39;')})'>이 주제로 시작</button></div>`).join('');document.getElementById('recommendNav').innerHTML=`<button class="btn secondary" onclick="showRecommendationPage(-1)" ${recommendationPage===0?'disabled':''}>이전</button><span class="page-info">${recommendationPage+1}/${pages}</span><button class="btn" onclick="showRecommendationPage(1)" ${recommendationPage>=pages-1?'disabled':''}>다음</button>`;}
function showRecommendationPage(d){const pages=Math.max(1,Math.ceil(recommendedItems.length/PAGE_SIZE));recommendationPage=Math.max(0,Math.min(pages-1,recommendationPage+d));renderRecommendations();}
async function startProject(it){const q=getInterestQuery();const res=await post('/api/projects',{student_id:currentStudent.id,tag:q.tagText,interest:q.detail,topic:it.topic,subject:it.subject||'',fit_score:it.fit?.total||70});location.href=`wizard.html?project_id=${res.project_id}`;}
async function initWizardPage(){if(!document.getElementById('projectBox'))return;const id=new URLSearchParams(location.search).get('project_id');if(!id)return;await loadWizardProject(id);}async function loadWizardProject(id){const p=await(await fetch(`/api/projects/${id}`)).json();currentProjectId=p.id;document.getElementById('projectTopic').innerText=p.topic;['plan','planNote','guideNote','surveyNote','interviewNote','log','reportNote'].forEach((id2)=>setValue(id2,p[id2==='log'?'research_log':id2.replace(/[A-Z]/g,m=>'_'+m.toLowerCase())]));document.getElementById('reportOutput').innerHTML=p.report?`<pre>${esc(p.report)}</pre>`:'';setWizardStep(p.progress>=100?6:p.progress>=90?5:p.progress>=80?4:p.progress>=70?3:p.progress>=60?2:p.progress>=45?1:0,p.progress||30);}
function setWizardStep(step,progress){currentWizardStep=Math.max(0,Math.min(6,step));WIZARD_PAGES.forEach((id,i)=>document.getElementById(id)?.classList.toggle('hidden',i!==currentWizardStep));document.querySelectorAll('#wizardStepper span').forEach((x,i)=>{x.classList.toggle('active',i===currentWizardStep);x.classList.toggle('done',i<currentWizardStep);});document.getElementById('prevWizardBtn').disabled=currentWizardStep===0;document.getElementById('nextWizardBtn').innerText=currentWizardStep===6?'완료':'다음';updateProgress(progress??WIZARD_PROGRESS[currentWizardStep]);if(currentWizardStep===6)renderPrintSummary();}
function autoProgress(){let p=WIZARD_PROGRESS[currentWizardStep]||30;if(valueOf('planNote'))p=Math.max(p,45);if(valueOf('guideNote'))p=Math.max(p,55);if(valueOf('surveyNote'))p=Math.max(p,65);if(valueOf('interviewNote'))p=Math.max(p,75);if(valueOf('log'))p=Math.max(p,80);if(valueOf('reportNote')||document.getElementById('reportOutput')?.innerText)p=Math.max(p,90);if(currentWizardStep===6)p=100;updateProgress(p);return p;}function updateProgress(p){p=clamp(p);document.getElementById('progressText').innerText=`진행률 ${p}%`;document.getElementById('progressBar').style.width=`${p}%`;}
async function saveProject(progress=autoProgress(),showAlert=false){const body={plan:valueOf('plan'),plan_note:valueOf('planNote'),guide_note:valueOf('guideNote'),survey_note:valueOf('surveyNote'),interview_note:valueOf('interviewNote'),research_log:valueOf('log'),report:document.getElementById('reportOutput')?.innerText||'',report_note:valueOf('reportNote'),progress};const res=await fetch(`/api/projects/${currentProjectId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)return alert('저장 실패');updateProgress(progress);if(showAlert)alert('저장되었습니다.');}
async function nextWizardStep(){await saveProject(WIZARD_PROGRESS[currentWizardStep]);if(currentWizardStep<6)setWizardStep(currentWizardStep+1);else alert('완료 내용이 저장되었습니다.');}async function prevWizardStep(){await saveProject(WIZARD_PROGRESS[currentWizardStep]);setWizardStep(currentWizardStep-1);}
async function loadGuide(){const r=await(await fetch(`/api/projects/${currentProjectId}/guide`)).json();document.getElementById('guideOutput').innerHTML=`<div class="result"><ol>${r.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`;}async function loadSurvey(){const r=await(await fetch(`/api/projects/${currentProjectId}/survey`)).json();document.getElementById('surveyOutput').innerHTML=`<div class="result"><ol>${r.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`;}async function loadInterview(){const r=await(await fetch(`/api/projects/${currentProjectId}/interview`)).json();document.getElementById('interviewOutput').innerHTML=`<div class="result"><ol>${r.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`;}async function makeReport(){await saveProject(80);const r=await post(`/api/projects/${currentProjectId}/report`,{});document.getElementById('reportOutput').innerHTML=`<pre>${esc(r.report)}</pre>`;setWizardStep(5,90);}
function section(title,text){return `<section><h3>${title}</h3><div class="summary-text">${esc(text||'아직 작성된 내용이 없습니다.')}</div></section>`;}function renderPrintSummary(){const b=document.getElementById('printSummary');if(!b)return;b.innerHTML=`<h2>AI 탐구메이트 정리내용</h2><p><b>탐구 주제</b> ${esc(document.getElementById('projectTopic').innerText)}</p>${section('탐구계획서',valueOf('plan'))}${section('계획서 메모',valueOf('planNote'))}${section('자료조사 메모',valueOf('guideNote'))}${section('설문 메모',valueOf('surveyNote'))}${section('인터뷰 메모',valueOf('interviewNote'))}${section('탐구일지',valueOf('log'))}${section('보고서 초안',document.getElementById('reportOutput')?.innerText||'')}${section('보고서 정리 메모',valueOf('reportNote'))}`;}async function printSummary(){await saveProject(100);renderPrintSummary();window.print();}
async function teacherLogin(){const r=await post('/api/teacher/login',{password:valueOf('teacherPw')});if(!r.ok)return alert('비밀번호가 올바르지 않습니다.');teacherPassword=valueOf('teacherPw');sessionStorage.setItem('teacherPassword',teacherPassword);document.getElementById('teacherLogin').classList.add('hidden');document.getElementById('dash').classList.remove('hidden');await loadDashboard();}
function renderUpdates(u=[]){return u.map(x=>`<div class="update-item"><b>${esc(x.created_at)}</b><p>${esc(x.summary)}</p><small>${esc(x.changed_text)}</small></div>`).join('')||'<p class="muted">저장 이력이 없습니다.</p>';}function renderTeacherFeedback(f=[]){return f.slice(0,3).map(x=>`<div class="teacher-feedback-item"><b>${esc(x.created_at)} · ${x.total_score||0}/20점</b><p>${esc(x.teacher_comment||'')}</p></div>`).join('')||'<p class="muted">아직 피드백이 없습니다.</p>';}
async function loadDashboard(){const r=await(await fetch('/api/teacher/dashboard')).json();document.getElementById('dashboard').innerHTML=`<table class="table"><tr><th>학생</th><th>주제</th><th>진행 상황</th><th>점수</th><th class="no-print">피드백</th></tr>${(r.items||[]).map(x=>`<tr><td><b>${esc(x.name)}</b><br>${esc(x.student_no)}</td><td>${esc(x.topic)}</td><td>${esc(x.progress_note||'')}</strong><p class="muted">최근 저장: ${esc(x.updated_at)}</p>${renderUpdates(x.updates)}</td><td>${x.fit_score}점<br>${x.progress}%<div class="bar"><span style="width:${clamp(x.progress)}%"></span></div></td><td class="no-print"><textarea class="teacher-comment" id="c${x.id}" placeholder="교사 피드백"></textarea><div class="rubric-form">${['problem_def','data_collection','analysis','communication'].map((k,i)=>`<label>${['문제 설정','자료 수집','분석','의사소통'][i]}<select class="rubric-select" id="r_${k}_${x.id}">${[0,1,2,3,4,5].map(v=>`<option value="${v}">${v}점</option>`).join('')}</select></label>`).join('')}</div><button class="btn secondary" onclick="saveFeedback(${x.id})">피드백 저장</button>${renderTeacherFeedback(x.feedbacks)}</td></tr>`).join('')}</table>`;}
async function saveFeedback(id){const payload={teacher_comment:valueOf(`c${id}`),problem_def:Number(valueOf(`r_problem_def_${id}`)),data_collection:Number(valueOf(`r_data_collection_${id}`)),analysis:Number(valueOf(`r_analysis_${id}`)),communication:Number(valueOf(`r_communication_${id}`))};if(!payload.teacher_comment&&payload.problem_def+payload.data_collection+payload.analysis+payload.communication===0)return alert('피드백이나 점수를 입력하세요.');await post(`/api/projects/${id}/feedback`,payload);alert('저장되었습니다.');await loadDashboard();}
function saveDashboardPdf(){window.print();}async function resetStudentData(){if(!teacherPassword)return alert('교사 로그인 후 사용할 수 있습니다.');if(!confirm('모든 학생 자료를 삭제할까요?'))return;await post('/api/teacher/reset',{password:teacherPassword});await loadDashboard();}
async function aiSettingsLogin(){const r=await post('/api/teacher/login',{password:valueOf('aiSettingsPw')});if(!r.ok)return alert('비밀번호가 올바르지 않습니다.');teacherPassword=valueOf('aiSettingsPw');sessionStorage.setItem('teacherPassword',teacherPassword);document.getElementById('aiSettingsLogin').classList.add('hidden');document.getElementById('aiSettingsBox').classList.remove('hidden');await loadAiSettings();}async function initAiSettingsPage(){if(!document.getElementById('aiSettingsLogin'))return;teacherPassword=sessionStorage.getItem('teacherPassword')||'';if(teacherPassword){document.getElementById('aiSettingsLogin').classList.add('hidden');document.getElementById('aiSettingsBox').classList.remove('hidden');await loadAiSettings();}}
async function loadAiSettings(){if(!teacherPassword)return;const r=await post('/api/teacher/ai-settings',{password:teacherPassword});setValue('aiModel',r.model||'gpt-4o-mini');document.getElementById('onlineAiEnabled').checked=!!r.online_ai_enabled;document.getElementById('aiKeyHint').innerText=r.has_api_key?`저장된 키: ${r.masked_api_key}`:'저장된 API 키가 없습니다.';document.getElementById('aiSettingsStatus').innerText=r.online_ai_enabled&&r.has_api_key?'온라인 AI 사용 중':'오프라인 추천 엔진 사용 중';}
async function saveAiSettings(){const r=await post('/api/teacher/ai-settings/save',{password:teacherPassword,online_ai_enabled:document.getElementById('onlineAiEnabled').checked,openai_api_key:valueOf('aiApiKey'),clear_api_key:document.getElementById('clearAiKey').checked,model:valueOf('aiModel')||'gpt-4o-mini'});if(!r.ok)return alert('저장 실패');alert('AI 설정이 저장되었습니다.');await loadAiSettings();}
